from langchain_ollama import OllamaLLM


class Ai_chat(object):
    """
    A class to interface Ollama - langchain
    """

    llm=None

    def __init__(self):
        llm = OllamaLLM(model="llama3.2:1b", prepend_text='')
        self.llm = llm
    
    def generate_poem(self, poem_of):
        """Generate poems based on the description provided

        Args:
            poem_of (str): A description of an object that will be turned into a poem

        Returns:
            str: A poem generated by LLM
        """
        return self.llm.invoke(f"Tell me two stanza poem about {poem_of}. Poem only no other propts")
